name: SDG

generation_settings:
  num_images: 1000
  prim_path: Camera
  camera_names: [camera_annotations]
  camera_resolutions: [[640, 480]]
  data_dir: data
  annotators_list: [["rgb", "semantic_segmentation", "instance_segmentation"]]
  image_formats: [png]
  annot_formats: [json]
  element_per_folder: 1000
  save_intrinsics: true

camera_settings:
  camera_path: Camera/camera_annotations
  focal_length: 1.93
  horizontal_aperture: 3.6
  vertical_aperture: 2.7
  fstop: 0.0
  focus_distance: 10.0
  clipping_range: [0.01, 1000000.0]
